### ISSUE TITLE
move all images/assets from external resouces into codebase

### ISSUE THREAD

**Issue by anchaked** [Learning-By-Doing-Never-Googling-Alone/ChatApp#22]
if we can, of course

**Comment by Illuminati9** [comment]
hey @anchaked , I want to work on this issue, Can you please assign it to me and can you please explain this issue in detail. :)

**Comment by Illuminati9** [comment]
Can you please explain about this issue in detail :)

**Comment by beamwarisara** [comment]
Currently, some images are used by referring to external sources, such as imgbb. I think It would be better to copy all that images and put them into this project directly, that is what I chat with Ked

**Comment by anchaked** [comment]
yes, correct. we need to walk through the codebase and find those references. It might be on img tag or in CSS or as background image.

**Comment by Illuminati9** [comment]
can you please mention the tech stacks used for this project

**Comment by anchaked** [comment]
It is react for FE and supabase for BE, with supabase if we need some APIs it would node.js
